SUPPORTED_LANGUAGES = ["ja", "en", "fr", "es", "ko"]

TRANSLATIONS = {
    "ja": {
        "app_name": "Voice In",
        "tooltip_hold_key": "設定されたキーを押している間、録音して文字起こしします",
        "tray_setup": "セットアップ...",
        "tray_settings": "設定...",
        "tray_history": "履歴...",
        "tray_last_result": "直近の結果...",
        "tray_current": "現在: {provider}",
        "tray_switch_gemini": "Gemini に切替",
        "tray_switch_groq": "Groq に切替",
        "tray_switch_local": "Local に切替",
        "tray_show_hide": "表示/非表示",
        "tray_quit": "終了",
        "ctx_setup": "セットアップ...",
        "ctx_settings": "設定...",
        "ctx_history": "履歴...",
        "ctx_last_result": "直近の結果...",
        "ctx_current": "現在: {provider}",
        "ctx_quit": "終了",
        "switch_to_gemini": "Gemini に切替",
        "switch_to_groq": "Groq に切替",
        "switch_to_local": "Local に切替",
        "history_title": "履歴",
        "history_search": "検索",
        "history_search_ph": "検索...",
        "history_col_time": "日時",
        "history_col_provider": "プロバイダ",
        "history_col_type": "種別",
        "history_col_preview": "プレビュー",
        "history_copy": "コピー",
        "history_close": "閉じる",
        "history_no_history": "履歴はありません。",
        "last_result_title": "直近の結果",
        "last_result_copy": "コピー",
        "last_result_close": "閉じる",
        "last_result_no_result": "まだ結果がありません。",
        "settings_title": "Voice In 設定",
        "settings_save_apply": "保存して適用",
        "settings_close": "閉じる",
        "tab_general": "一般",
        "tab_prompts": "プロンプト",
        "tab_dictionary": "辞書",
        "tab_tests": "テスト",
        "label_ai_provider": "AI プロバイダ",
        "label_gemini_model": "Gemini モデル",
        "label_groq_key": "Groq API Key",
        "label_gemini_key": "Gemini API Key",
        "label_local_model_size": "モデルサイズ",
        "label_local_device": "デバイス",
        "label_local_compute_type": "計算タイプ",
        "label_input_device": "入力デバイス",
        "label_input_gain": "入力ゲイン",
        "label_hold_key": "録音キー",
        "label_max_recording": "最大録音",
        "label_min_duration": "最小有効録音時間",
        "label_auto_paste": "自動貼り付け",
        "label_paste_delay": "貼り付け遅延",
        "label_language": "表示言語",
        "btn_refresh": "更新",
        "dict_from": "置換前",
        "dict_to": "置換後",
        "dict_add": "追加",
        "dict_remove": "削除",
        "tests_mic_title": "マイク入力テスト",
        "tests_mic_start": "テスト開始",
        "tests_mic_stop": "テスト停止",
        "tests_accuracy_title": "文字起こし精度テスト",
        "tests_rec_start": "録音開始",
        "tests_stop": "停止",
        "tests_transcribe": "文字起こし",
        "tests_result_ph": "ここに文字起こし結果が表示されます",
        "saved_title": "保存",
        "saved_message": "設定を保存して適用しました。",
        "warning_title": "警告",
        "tab_categories": "カテゴリ",
        "cat_title": "アプリカテゴリ",
        "cat_context_aware": "コンテキスト認識によるプロンプト最適化を有効にする",
        "cat_category": "カテゴリ",
        "cat_dev": "DEV - 開発・コーディング",
        "cat_biz": "BIZ - ビジネス・連絡",
        "cat_doc": "DOC - 文書作成・メモ",
        "cat_std": "STD - 標準",
        "cat_keywords_label": "キーワード（マッチするアプリはこのカテゴリを使用）:",
        "cat_keyword": "キーワード",
        "cat_add_keyword": "+ キーワード追加",
        "cat_remove": "- 削除",
        "cat_prompt_label": "カテゴリプロンプト（このカテゴリ検出時に使用）:",
        "cat_detected_apps": "検出済みアプリ履歴",
        "cat_app_name": "アプリ名",
        "cat_auto_category": "自動カテゴリ",
        "cat_assigned_category": "割り当てカテゴリ",
        "cat_assign": "カテゴリに割り当て",
        "cat_clear_history": "履歴をクリア",
        "cat_clear_confirm": "検出済みアプリ履歴をすべてクリアしますか？",
        "cat_assigned_msg": "'{app}' を {category} カテゴリのキーワードに追加しました。",
        "setup_title": "Voice In - セットアップウィザード",
        "setup_back": "← 戻る",
        "setup_next": "次へ →",
        "setup_cancel": "キャンセル",
        "setup_finish": "完了",
        "setup_welcome_title": "🎤 Voice In へようこそ",
        "setup_welcome_subtitle": "AI音声入力ツール",
        "setup_welcome_body": "このウィザードでは初期設定を行います:\n\n✨ AIプロバイダとAPIキーの設定\n🎙️ マイクの選択\n⌨️ ホットキーと貼り付けオプションの設定",
        "setup_lang_title": "🌐 言語設定",
        "setup_lang_select": "表示言語を選択してください:",
        "setup_provider_title": "🤖 AIプロバイダ設定",
        "setup_provider": "AIプロバイダ:",
        "setup_gemini_model": "Gemini モデル:",
        "setup_groq_key": "Groq API Key:",
        "setup_gemini_key": "Gemini API Key:",
        "setup_local_note": "ℹ️ Local Whisperを使用するには 'faster-whisper' のインストールが必要です。デフォルトモデル: large-v3。",
        "setup_download_model": "⬇️ モデルをダウンロード",
        "setup_downloading": "モデルをダウンロード中... 数分かかる場合があります。",
        "setup_download_success": "✅ モデルのダウンロードが完了しました！",
        "setup_download_failed": "❌ モデルのダウンロードに失敗しました。ログを確認してください。",
        "setup_mic_title": "🎙️ マイク設定",
        "setup_input_device": "入力デバイス:",
        "setup_refresh": "🔄 更新",
        "setup_mic_test": "マイクテスト:",
        "setup_mic_start": "▶️ テスト開始",
        "setup_mic_stop": "⏹️ テスト停止",
        "setup_controls_title": "⌨️ 操作設定",
        "setup_hold_key": "録音キー:",
        "setup_max_recording": "最大録音時間:",
        "setup_auto_paste": "文字起こしテキストを自動で貼り付ける",
        "setup_finish_title": "✅ セットアップ完了！",
        "setup_finish_body": "すべての設定が完了しました。\n\n「完了」をクリックして設定を保存し、Voice Inを使い始めましょう。\n\nこれらの設定はシステムトレイメニューからいつでも変更できます。",
        "setup_missing_dep": "依存関係が不足しています",
        "setup_missing_dep_msg": "faster-whisperがインストールされていません。\n\n以下のコマンドでインストールしてください:\npip install faster-whisper",
        "setup_download_error": "ダウンロードエラー",
    },
    "en": {
        "app_name": "Voice In",
        "tooltip_hold_key": "Hold the configured key to record and transcribe",
        "tray_setup": "Setup Wizard...",
        "tray_settings": "Settings...",
        "tray_history": "History...",
        "tray_last_result": "Show Last Result...",
        "tray_current": "Current: {provider}",
        "tray_switch_gemini": "Switch to Gemini",
        "tray_switch_groq": "Switch to Groq",
        "tray_switch_local": "Switch to Local",
        "tray_show_hide": "Show/Hide",
        "tray_quit": "Quit",
        "ctx_setup": "Setup Wizard...",
        "ctx_settings": "Settings...",
        "ctx_history": "History...",
        "ctx_last_result": "Show Last Result...",
        "ctx_current": "Current: {provider}",
        "ctx_quit": "Quit",
        "switch_to_gemini": "Switch to Gemini",
        "switch_to_groq": "Switch to Groq",
        "switch_to_local": "Switch to Local",
        "history_title": "History",
        "history_search": "Search",
        "history_search_ph": "Search...",
        "history_col_time": "Time",
        "history_col_provider": "Provider",
        "history_col_type": "Type",
        "history_col_preview": "Preview",
        "history_copy": "Copy",
        "history_close": "Close",
        "history_no_history": "No history yet.",
        "last_result_title": "Last Result",
        "last_result_copy": "Copy",
        "last_result_close": "Close",
        "last_result_no_result": "No result yet.",
        "settings_title": "Voice In Settings",
        "settings_save_apply": "Save & Apply",
        "settings_close": "Close",
        "tab_general": "General",
        "tab_prompts": "Prompts",
        "tab_dictionary": "Dictionary",
        "tab_tests": "Tests",
        "label_ai_provider": "AI Provider",
        "label_gemini_model": "Gemini Model",
        "label_groq_key": "Groq API Key",
        "label_gemini_key": "Gemini API Key",
        "label_local_model_size": "Model Size",
        "label_local_device": "Device",
        "label_local_compute_type": "Compute Type",
        "label_input_device": "Input Device",
        "label_input_gain": "Input Gain",
        "label_hold_key": "Hold Key",
        "label_max_recording": "Max Recording",
        "label_min_duration": "Min Valid Duration",
        "label_auto_paste": "Auto Paste",
        "label_paste_delay": "Paste Delay",
        "label_language": "Language",
        "btn_refresh": "Refresh",
        "dict_from": "From",
        "dict_to": "To",
        "dict_add": "Add",
        "dict_remove": "Remove",
        "tests_mic_title": "Microphone Input Test",
        "tests_mic_start": "Start Mic Test",
        "tests_mic_stop": "Stop Mic Test",
        "tests_accuracy_title": "Transcription Accuracy Test",
        "tests_rec_start": "Start Recording",
        "tests_stop": "Stop",
        "tests_transcribe": "Transcribe",
        "tests_result_ph": "Transcription result will appear here",
        "saved_title": "Saved",
        "saved_message": "Settings saved and applied.",
        "warning_title": "Warning",
        "tab_categories": "Categories",
        "cat_title": "App Categories",
        "cat_context_aware": "Enable context-aware prompt optimization",
        "cat_category": "Category",
        "cat_dev": "DEV - Development",
        "cat_biz": "BIZ - Business",
        "cat_doc": "DOC - Documents",
        "cat_std": "STD - Standard",
        "cat_keywords_label": "Keywords (apps matching these will use this category):",
        "cat_keyword": "Keyword",
        "cat_add_keyword": "+ Add Keyword",
        "cat_remove": "- Remove",
        "cat_prompt_label": "Category Prompt (used when this category is detected):",
        "cat_detected_apps": "Detected Apps History",
        "cat_app_name": "App Name",
        "cat_auto_category": "Auto Category",
        "cat_assigned_category": "Assigned Category",
        "cat_assign": "Assign to Category",
        "cat_clear_history": "Clear History",
        "cat_clear_confirm": "Clear all detected apps history?",
        "cat_assigned_msg": "'{app}' has been added to {category} category keywords.",
        "setup_title": "Voice In - Setup Wizard",
        "setup_back": "← Back",
        "setup_next": "Next →",
        "setup_cancel": "Cancel",
        "setup_finish": "Finish",
        "setup_welcome_title": "🎤 Welcome to Voice In",
        "setup_welcome_subtitle": "AI-powered Voice Dictation Tool",
        "setup_welcome_body": "This wizard will guide you through the initial setup:\n\n✨ Configure AI provider and API key\n🎙️ Select your microphone\n⌨️ Configure hotkey and paste options",
        "setup_lang_title": "🌐 Language Settings",
        "setup_lang_select": "Select your display language:",
        "setup_provider_title": "🤖 AI Provider Configuration",
        "setup_provider": "AI Provider:",
        "setup_gemini_model": "Gemini Model:",
        "setup_groq_key": "Groq API Key:",
        "setup_gemini_key": "Gemini API Key:",
        "setup_local_note": "ℹ️ Local Whisper requires 'faster-whisper' installed. Default model: large-v3.",
        "setup_download_model": "⬇️ Download Model",
        "setup_downloading": "Downloading model... This may take several minutes.",
        "setup_download_success": "✅ Model downloaded successfully!",
        "setup_download_failed": "❌ Model download failed. Please check the logs.",
        "setup_mic_title": "🎙️ Microphone Configuration",
        "setup_input_device": "Input Device:",
        "setup_refresh": "🔄 Refresh",
        "setup_mic_test": "Microphone Test:",
        "setup_mic_start": "▶️ Start Mic Test",
        "setup_mic_stop": "⏹️ Stop Mic Test",
        "setup_controls_title": "⌨️ Control Settings",
        "setup_hold_key": "Hold Key:",
        "setup_max_recording": "Max Recording Time:",
        "setup_auto_paste": "Automatically paste transcribed text",
        "setup_finish_title": "✅ Setup Complete!",
        "setup_finish_body": "All settings have been configured.\n\nClick 'Finish' to save your settings and start using Voice In.\n\nYou can change these settings anytime from the system tray menu.",
        "setup_missing_dep": "Missing Dependency",
        "setup_missing_dep_msg": "faster-whisper is not installed.\n\nPlease install it with:\npip install faster-whisper",
        "setup_download_error": "Download Error",
    },
    "fr": {
        "app_name": "Voice In",
        "tooltip_hold_key": "Maintenez la touche configurée pour enregistrer et transcrire",
        "tray_setup": "Assistant de configuration...",
        "tray_settings": "Paramètres...",
        "tray_history": "Historique...",
        "tray_last_result": "Dernier résultat...",
        "tray_current": "Actuel : {provider}",
        "tray_switch_gemini": "Passer à Gemini",
        "tray_switch_groq": "Passer à Groq",
        "tray_switch_local": "Passer à Local",
        "tray_show_hide": "Afficher/Masquer",
        "tray_quit": "Quitter",
        "ctx_setup": "Assistant de configuration...",
        "ctx_settings": "Paramètres...",
        "ctx_history": "Historique...",
        "ctx_last_result": "Dernier résultat...",
        "ctx_current": "Actuel : {provider}",
        "ctx_quit": "Quitter",
        "switch_to_gemini": "Passer à Gemini",
        "switch_to_groq": "Passer à Groq",
        "switch_to_local": "Passer à Local",
        "history_title": "Historique",
        "history_search": "Rechercher",
        "history_search_ph": "Rechercher...",
        "history_col_time": "Heure",
        "history_col_provider": "Fournisseur",
        "history_col_type": "Type",
        "history_col_preview": "Aperçu",
        "history_copy": "Copier",
        "history_close": "Fermer",
        "history_no_history": "Aucun historique.",
        "last_result_title": "Dernier résultat",
        "last_result_copy": "Copier",
        "last_result_close": "Fermer",
        "last_result_no_result": "Aucun résultat.",
        "settings_title": "Paramètres Voice In",
        "settings_save_apply": "Enregistrer et appliquer",
        "settings_close": "Fermer",
        "tab_general": "Général",
        "tab_prompts": "Prompts",
        "tab_dictionary": "Dictionnaire",
        "tab_tests": "Tests",
        "label_ai_provider": "Fournisseur IA",
        "label_gemini_model": "Modèle Gemini",
        "label_groq_key": "Clé API Groq",
        "label_gemini_key": "Clé API Gemini",
        "label_local_model_size": "Taille Modèle",
        "label_local_device": "Device",
        "label_local_compute_type": "Type de calcul",
        "label_input_device": "Périphérique d'entrée",
        "label_input_gain": "Gain d'entrée",
        "label_hold_key": "Touche d'appui",
        "label_max_recording": "Enregistrement max",
        "label_auto_paste": "Coller automatiquement",
        "label_paste_delay": "Délai de collage",
        "label_language": "Langue",
        "btn_refresh": "Rafraîchir",
        "dict_from": "De",
        "dict_to": "À",
        "dict_add": "Ajouter",
        "dict_remove": "Supprimer",
        "tests_mic_title": "Test micro",
        "tests_mic_start": "Démarrer test micro",
        "tests_mic_stop": "Arrêter test micro",
        "tests_accuracy_title": "Test de transcription",
        "tests_rec_start": "Démarrer l'enregistrement",
        "tests_stop": "Arrêter",
        "tests_transcribe": "Transcrire",
        "tests_result_ph": "Le résultat apparaîtra ici",
        "saved_title": "Enregistré",
        "saved_message": "Paramètres enregistrés et appliqués.",
        "warning_title": "Avertissement",
    },
    "es": {
        "app_name": "Voice In",
        "tooltip_hold_key": "Mantén la tecla configurada para grabar y transcribir",
        "tray_setup": "Asistente de configuración...",
        "tray_settings": "Configuración...",
        "tray_history": "Historial...",
        "tray_last_result": "Último resultado...",
        "tray_current": "Actual: {provider}",
        "tray_switch_gemini": "Cambiar a Gemini",
        "tray_switch_groq": "Cambiar a Groq",
        "tray_switch_local": "Cambiar a Local",
        "tray_show_hide": "Mostrar/Ocultar",
        "tray_quit": "Salir",
        "ctx_setup": "Asistente de configuración...",
        "ctx_settings": "Configuración...",
        "ctx_history": "Historial...",
        "ctx_last_result": "Último resultado...",
        "ctx_current": "Actual: {provider}",
        "ctx_quit": "Salir",
        "switch_to_gemini": "Cambiar a Gemini",
        "switch_to_groq": "Cambiar a Groq",
        "switch_to_local": "Cambiar a Local",
        "history_title": "Historial",
        "history_search": "Buscar",
        "history_search_ph": "Buscar...",
        "history_col_time": "Hora",
        "history_col_provider": "Proveedor",
        "history_col_type": "Tipo",
        "history_col_preview": "Vista previa",
        "history_copy": "Copiar",
        "history_close": "Cerrar",
        "history_no_history": "No hay historial.",
        "last_result_title": "Último resultado",
        "last_result_copy": "Copiar",
        "last_result_close": "Cerrar",
        "last_result_no_result": "Sin resultados.",
        "settings_title": "Configuración de Voice In",
        "settings_save_apply": "Guardar y aplicar",
        "settings_close": "Cerrar",
        "tab_general": "General",
        "tab_prompts": "Prompts",
        "tab_dictionary": "Diccionario",
        "tab_tests": "Pruebas",
        "label_ai_provider": "Proveedor de IA",
        "label_gemini_model": "Modelo Gemini",
        "label_groq_key": "Clave API Groq",
        "label_gemini_key": "Clave API Gemini",
        "label_local_model_size": "Tamaño del Modelo",
        "label_local_device": "Dispositivo",
        "label_local_compute_type": "Tipo de computación",
        "label_input_device": "Dispositivo de entrada",
        "label_input_gain": "Ganancia de entrada",
        "label_hold_key": "Tecla",
        "label_max_recording": "Grabación máx.",
        "label_auto_paste": "Pegar automáticamente",
        "label_paste_delay": "Retardo de pegado",
        "label_language": "Idioma",
        "btn_refresh": "Actualizar",
        "dict_from": "De",
        "dict_to": "A",
        "dict_add": "Añadir",
        "dict_remove": "Eliminar",
        "tests_mic_title": "Prueba de micrófono",
        "tests_mic_start": "Iniciar prueba",
        "tests_mic_stop": "Detener prueba",
        "tests_accuracy_title": "Prueba de transcripción",
        "tests_rec_start": "Iniciar grabación",
        "tests_stop": "Detener",
        "tests_transcribe": "Transcribir",
        "tests_result_ph": "El resultado aparecerá aquí",
        "saved_title": "Guardado",
        "saved_message": "Configuración guardada y aplicada.",
        "warning_title": "Aviso",
    },
    "ko": {
        "app_name": "Voice In",
        "tooltip_hold_key": "설정된 키를 누르는 동안 녹음 및 전사합니다",
        "tray_setup": "설정 마법사...",
        "tray_settings": "설정...",
        "tray_history": "기록...",
        "tray_last_result": "최근 결과...",
        "tray_current": "현재: {provider}",
        "tray_switch_gemini": "Gemini로 전환",
        "tray_switch_groq": "Groq로 전환",
        "tray_switch_local": "Local로 전환",
        "tray_show_hide": "표시/숨기기",
        "tray_quit": "종료",
        "ctx_setup": "설정 마법사...",
        "ctx_settings": "설정...",
        "ctx_history": "기록...",
        "ctx_last_result": "최근 결과...",
        "ctx_current": "현재: {provider}",
        "ctx_quit": "종료",
        "switch_to_gemini": "Gemini로 전환",
        "switch_to_groq": "Groq로 전환",
        "switch_to_local": "Local로 전환",
        "history_title": "기록",
        "history_search": "검색",
        "history_search_ph": "검색...",
        "history_col_time": "시간",
        "history_col_provider": "제공자",
        "history_col_type": "종류",
        "history_col_preview": "미리보기",
        "history_copy": "복사",
        "history_close": "닫기",
        "history_no_history": "기록이 없습니다.",
        "last_result_title": "최근 결과",
        "last_result_copy": "복사",
        "last_result_close": "닫기",
        "last_result_no_result": "결과가 없습니다.",
        "settings_title": "Voice In 설정",
        "settings_save_apply": "저장 및 적용",
        "settings_close": "닫기",
        "tab_general": "일반",
        "tab_prompts": "프롬프트",
        "tab_dictionary": "사전",
        "tab_tests": "테스트",
        "label_ai_provider": "AI 제공자",
        "label_gemini_model": "Gemini 모델",
        "label_groq_key": "Groq API 키",
        "label_gemini_key": "Gemini API 키",
        "label_local_model_size": "모델 크기",
        "label_local_device": "기기",
        "label_local_compute_type": "계산 유형",
        "label_input_device": "입력 장치",
        "label_input_gain": "입력 게인",
        "label_hold_key": "키",
        "label_max_recording": "최대 녹음",
        "label_auto_paste": "자동 붙여넣기",
        "label_paste_delay": "붙여넣기 지연",
        "label_language": "언어",
        "btn_refresh": "새로 고침",
        "dict_from": "변경 전",
        "dict_to": "변경 후",
        "dict_add": "추가",
        "dict_remove": "삭제",
        "tests_mic_title": "마이크 테스트",
        "tests_mic_start": "테스트 시작",
        "tests_mic_stop": "테스트 중지",
        "tests_accuracy_title": "전사 테스트",
        "tests_rec_start": "녹음 시작",
        "tests_stop": "중지",
        "tests_transcribe": "전사",
        "tests_result_ph": "여기에 결과가 표시됩니다",
        "saved_title": "저장됨",
        "saved_message": "설정이 저장되고 적용되었습니다.",
        "warning_title": "경고",
    },
}

SAMPLE_RATE = 44100
